### ISSUE TITLE
Management of multiple obstacles

### ISSUE THREAD

**Issue by MattiaMagro** [nndei/dVRL_Neri#1]
Hi @nndei 

I have seen that in your codes, you have manage different targets. I would like to implement in a similar way a scene with more than one obstacle and, to do that, I have created the obstacle class in the Simobject.py file.
Do I have to change something else in other files or does the baseline-HER algorithm automatically recognize this class as obstacle to avoid?

Thanks in advance

**Comment by nndei** [comment]
Hello Mattia,

If I am not mistaken, you have created a general class that represents an obstacle in the simulator scene, and you have called that "obstacle". The name alone doesn't mean anything, though. 

To that, you need to add the obstacle itself in the simulation scene and get its handle inside the python class. You can do that following what's done in any other class in simObjects. From there, you can write all the necessary methods (obviously an init + some other ones you'll need).

The python scripts are there to control the scene externally. For anything, you will need to specify how to behave given specific constraints or conditions. For example, I have a class _collisionCheck_ which reads collision states from _collision objects_ that are created in the simulation scene, and does something with that information. 

So, no. The algorithms will not do anything on their own. You need to specify what you intend to do with the objects you create. 
By the way, HER is an algorithm that must be used alongside any other off-policy algorithm, like DDPG. HER only provides the logic to update the policies using the collected experiences, so it doesn't make sense on its own. 

I hope you have a clearer picture.

Regards,
Neri

**Comment by MattiaMagro** [comment]
Thank you @nndei for the quick response and sorry for the delay in my response, but I had to perform some trials on my scene. I have a couple of questions:
1) In your scene about kidney, I don't get the role of the grey shape around the kidney: is it something related to the check collision function?
<img width="883" alt="Screenshot 2020-12-14 at 17 04 00" src="https://user-images.githubusercontent.com/72915922/102104777-df421600-3e2e-11eb-8fec-116e32189905.png">

2) So, if I correctly understood, I have just to put in my scene the obstacle and modify the function SimObject.py in order to manage it. Then, if I want that the arm learns to avoid the obstacle when it wants to reach the target, I have just to modify the function PsmEnv_Position.py. Is it correct?

**Comment by nndei** [comment]
Hello Mattia,

In order: 
1. The mesh is the kidney. The kidney is see-through in order to concentrate on the "grey" cuboid. The cuboid is the approximation of the kidney's volume and is employed for dynamics computations following CoppeliaSim guides. I would suggest looking at their wiki on how to perform dynamics computations and how to set the scene for that. In a nutshell, the shape you want to be active for the dynamics computations (i.e. using the physics engine to react/bounce to collisions) must be simple in order to lower the overhead and should be the parent shape. Therefore, instead of using a complex shape like the kidney itself, which you can see has a very detailed mesh, I used a cuboid which is a primitive shape. So, performing those computations (if desired) will be less computationally costly. You set whether you run the simulation with the physics engine on or off with parameter dynamics enabled in the configuration file pick.py or reach.py.

2. You put an object in a scene. Then, you must define its class in simObjects. This class will include the init method plus all the methods you desire to call to employ that object or use the information it carries, e.g. in a file like PsmEnv_Position.py. If you want the arm to avoid the obstacle while moving for the target, there are a billion ways. I suggest you look at the literature and start with a very simple distance-based collision avoidance. Take your time to investigate, as you sound (that's ok) very new to the field. 

Remember that in my code the state is fully observed: we magically know all the variables (like the kidney's orientation, centre of mass position and so on). You don't know these things in real life. Depending on the level of your research, I suggest you start with fully observability, then investigate or discuss with your PI (if you are supervised) how you can move on to estimating the desired variables. 

Regards,
Neri
